### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by 0zguner**

### CODE REVIEW

**Comment by svdo** [comment]
Thanks @mzgnr! Did you happen to run the target "AllTests" in Xcode? When I try to do it, I get errors because apparently I cannot explicitly write a state into my `testStore` anymore with the newer ReSwift APIs?

**Comment by svdo** [comment]
Found a way to fix it.

**Comment by 0zguner** [comment]
@svdo sorry for late reply. yeah with the new version you cannot do that

**Comment by svdo** [comment]
Just released v2.2.0.

**Pull request merged**
